name: Benchmark History
on:
  push:
    branches:
      - master

permissions:
  contents: write
  deployments: write
  repository-projects: write

jobs:
  test:
    name: Run Criterion.rs benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Pnpm Cache
        uses: ./.github/actions/pnpm-cache

      - name: Run test
        run: |
          pnpm test:metric


      # - name: Store benchmark result
      #   uses: benchmark-action/github-action-benchmark@v1.14.0
      #   with:
      #     name: Rust Benchmark
      #     tool: "cargo"
      #     output-file-path: output.txt
      #     github-token: ${{ secrets.PR_STATS_COMMENT_TOKEN }}
      #     auto-push: true
      #     gh-repository: "github.com/speedy-js/metrics"
      #
      #     # Show alert with commit comment on detecting possible performance regression
      #     fail-on-alert: false

      # - name: Push benchmark result
      #   run: git push 'https:///speedy-js:${{ secrets.GITHUB_TOKEN }}@github.com/speedy-js/rspack.git' gh-pages:gh-pages

